### ISSUE TITLE
attack functionality  

### ISSUE THREAD

**Issue by JavaBaz** [JavaBaz/zoop#3]
We need to add a functionality to some animals to be able to attack other animal.
In order to that, first we need to add attackPower and defencePower to each animal, it must be between 0 to 5.
if a wild animal attack a non-wild animal, attackPower of offensive animal increase by one and defencePower of defender decrease by one (Also keep it in mind attackPower and defencePower ALWAYS must be between 0 to 5!)

**Comment by lohithasiripurapu** [comment]
Hey, is this an open issue? I'd like to work on it.

**Comment by JavaBaz** [comment]
Hi @lohithasiripurapu ! :D 

Yes, this issue is open, and I would be delighted to have you contribute! This repository is meant to be a collaborative project, so your input on demonstrating the four pillars of OOP would be very welcome. Feel free to dive in, and if you have any questions or need clarification, don’t hesitate to ask.

Thanks for your interest and contributions!

**Comment by AminHosseinniya** [comment]
Hey @JavaBaz and @lohithasiripurapu
I've submitted a pull request #4 that addresses this issue. It implements the attack ability for animals, ensuring that `attackPower` and `defencePower` values stay within the range of 1 to 5. Please review when you have a chance.
